---
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://185.228.234.104:5430/cloud
    username: deturpant
    password: dbpvded8
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 45MB
  jpa:
    hibernate:
      ddl-auto: update
token:
  signing:
    key: FcdkyLzkszlmSWLqVksxk9UtljHBPz0KuiWNObPRdvONXIhKBvbpgvHT18zIk13piOHObhxXqGGs5sOatMr1Nw
    jwtExpirationInMs: 30000000
